org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.1
forge_version_range=[47,)
loader_version_range=[47,)

kubejs_version=2001.6.5-build.16
kubejs_version_range=[2001.6.5-build.7,)
rhino_version=2001.2.3-build.10
rhino_version_range=[2001.2.3-build.3,)
architectury_version=9.2.14
architectury_version_range=[9.2.14,)

slash_blade_version=1.9.63
slash_blade_version_range=[1.9.63,)
mrqx_slash_blade_core_version=1.3.2
mrqx_slash_blade_core_version_range=[1.3.0,)

mod_id=slashbladejs
mod_name=SlashBlade JS
mod_license=GPL v3
mod_version=1.1.4
mod_group_id=net.mrqx.slashbladejs
mod_authors=mrqx0195
mod_description=KubeJS compat for SlashBlade
mod_file_name=SlashBladeJS
